#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();

//Register Commands
$application->add(new app\commands\KominfoFetchCommand());

$application->run();